version: "3"
    
tasks:
    build:
        desc: Build the app
        cmds:
        - go build -o bin/hashit main.go 

    run: 
        desc: Run the app
        cmds:
        - go run main.go

    bot:
        desc: Execute the bot
        cmds:
        - ./bin/hashit